import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve,render,stepsFor,quote,stationDefaults,migrateConfig} from '../src/scenario.js';
const recipes=JSON.parse(readFileSync(new URL('../dist/recipes.json',import.meta.url)));
test('99 stations have distinct inference ports; sz03 follows station suffix',()=>{const ports=Array.from({length:99},(_,i)=>resolve({station:`sz${String(i+1).padStart(2,'0')}`}).port);assert.equal(ports[2],5603);assert.equal(new Set(ports).size,99);});
test('local and remote modes generate consistent client/server commands',()=>{for(const mode of ['local','remote']){const c=resolve({mode,station:'sz08'});assert.equal(c.port,5608);assert.equal(c.host,mode==='local'?'127.0.0.1':'192.168.1.6');const sim=stepsFor(recipes.find(r=>r.id==='05-sim-teleop'),c);assert.equal(sim.some(s=>s.command?.startsWith('ssh')),mode==='remote');const evaluation=stepsFor(recipes.find(r=>r.id==='07-real-eval'),c).find(s=>s.command);assert.ok(evaluation.command.includes(`--policy_host='${c.host}' --policy_port='5608'`));}});
test('reject invalid stations, port conflicts, duplicate devices and malicious hosts',()=>{for(const input of [{station:'sz00'},{station:'sz100'},{station:'sz3'},{server:'x;rm -rf /'},{viewer:5603},{backend:0},{front:0},{robot:'/dev/ttyACM0'},{mode:'bad'},{teleopId:'$(id)'},{user:'-oProxyCommand=x'}])assert.throws(()=>resolve(input));});
test('shell quoting escapes apostrophes and wraps substitutions',()=>{const value="/models/it'sz a $(echo bad) `echo bad` checkpoint";const command=render('printf %s {{model}}',{model:value});assert.ok(command.includes(quote(value))); assert.ok(quote(value).includes("'\"'\"'"));assert.throws(()=>render('{{unknown}}',{}));});
test('every scenario and command template resolves without unresolved placeholders',()=>{for(const mode of ['remote','local']) for(const station of ['sz01','sz03','sz99']) for(const r of recipes) for(const s of stepsFor(r,resolve({mode,station}))){if(!s.command)continue;assert.ok(!s.command.includes('{{'));assert.ok(s.command.length>0);}});

test('station defaults follow IDs and reserve teacher port suffix',()=>{for(let n=1;n<=99;n++){const station=`sz${String(n).padStart(2,'0')}`;const c=resolve({station});assert.equal(c.user,'student');assert.equal(c.teleopId,`leader-${station}`);assert.equal(c.robotId,`follower-${station}`);assert.ok(c.calibration.endsWith(`leader-${station}.json`));assert.equal(+c.viewer,8200+n);assert.equal(+c.tunnel,18700+n);assert.equal(+c.backend,5500);assert.equal(+c.signal,49100+(n-1)*10);assert.equal(+c.media,47998+(n-1)*10);}});
test('user is configurable per workstation and not reset by station change',()=>{assert.equal(resolve({station:'sz03',user:'xutao'}).user,'xutao');const c=resolve({station:'sz08',user:'teacher'});assert.equal(c.user,'teacher');assert.equal(c.teleopId,'leader-sz08');});
test('viewer container overrides CMD to listen on per-station port',()=>{const c=resolve({station:'sz03'});const web=stepsFor(recipes.find(r=>r.id==='05-sim-teleop'),c).find(s=>s.title==='启动网页容器');assert.ok(web.command.includes('node_modules/.bin/vite'));assert.ok(web.command.includes("'8203'"));assert.ok(!web.command.includes('WEB_VIEWER_PORT'));});
test('sim container mounts host source for hotfix without rebuild',()=>{const c=resolve({station:'sz03'});const sim=stepsFor(recipes.find(r=>r.id==='05-sim-teleop'),c).find(s=>s.title==='启动仿真容器');assert.ok(sim.command.includes('/workspace/Sim-to-Real-SO-101-Workshop/source'));assert.ok(sim.command.includes(c.simSource));});
test('migrate old saved station and ignore hidden server in local mode',()=>{const c=migrateConfig({station:'s03',user:'student',viewer:'8210',tunnel:'18765',backend:'5554'});assert.equal(c.station,'sz03');assert.equal(c.user,'student');assert.equal(resolve(c).port,5603);assert.equal(resolve({mode:'local',server:''}).host,'127.0.0.1');});
