import courseRecipes from './catalog.js';
const recipes=[{id:'00-workstation',order:0,title:'配置你的实训场景',category:'sim2real',duration:'开始前配置',description:'设置工位、算力与设备参数，后续 sim2real 课程共用并自动保存这份配置。'},...courseRecipes];
import {lessonContent} from './lesson.js';
import {defaults,resolve,stationDefaults,migrateConfig} from './scenario.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config={...defaults},completed={};
try{config=migrateConfig(JSON.parse(localStorage.getItem('bridsimreal-scenario')||'{}'));completed=JSON.parse(localStorage.getItem('bridsimreal-progress')||'{}')||{};}catch{}
let active=null, selectedStep=0, searchQuery="", showCatalog=null;
function save(){try{localStorage.setItem('bridsimreal-scenario',JSON.stringify(config));localStorage.setItem('bridsimreal-progress',JSON.stringify(completed));}catch{}}
function toast(text){$('#toast').textContent=text;setTimeout(()=>$('#toast').textContent='',2500);}
function copy(text){const fail=()=>toast('无法访问剪贴板，请选中命令手动复制。'),ok=()=>toast('已复制');if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(ok,fail);return;}try{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();(document.execCommand('copy')?ok:fail)();ta.remove();}catch{fail();}}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function scenarioForm(){const input=(key,title,type='text')=>`<label>${title}<input name="${key}" type="${type}" value="${esc(config[key])}" ${type==='number'?'min="0"':''}></label>`;return `<section class="scenario" id="workstation"><div class="section-heading"><div><span class="eyebrow">YOUR WORKSTATION</span><h2>配置你的实训场景</h2></div><button id="reset" class="subtle">重置配置</button></div><form id="scenario"><div class="fields">${input('station','工位 ID · sz01–sz99')}<label>算力场景<select name="mode"><option value="remote" ${config.mode==='remote'?'selected':''}>端侧无 GPU · 集中服务器</option><option value="local" ${config.mode==='local'?'selected':''}>端侧有 GPU · 本机运行</option></select></label>${input('client','本机 IP')}${input('user','本机 SSH 账号')}</div><details class="advanced"><summary>设备与高级配置 <span>串口 / 相机 / 校准 / 端口</span></summary><div class="fields">${input('server','集中服务器 IP / 主机名')}${input('teleop','主臂串口')}${input('robot','从臂串口')}${input('teleopId','主臂校准 ID')}${input('robotId','从臂校准 ID')}${input('wrist','腕部相机索引','number')}${input('front','外部相机索引','number')}${input('viewer','教师分配的网页端口','number')}${input('tunnel','服务器主臂隧道端口','number')}${input('backend','推理后端端口','number')}${input('calibration','主臂校准 JSON 绝对路径')}${input('modelRoot','宿主机模型目录（挂载到 /workspace/models）')}${input('simSource','宿主机仿真源码目录（挂载到容器内源码）')}${input('model','容器内模型 checkpoint 路径')}</div><p class="muted">工位变更会同步填写主从臂校准 ID、校准路径及网页和隧道端口；已有设备可再手动修改。学生端口按 01–99 分配：网页 82xx、隧道 187xx、推理 56xx，WebRTC 信令 / 媒体在 49xxx / 47xxx 按工位错开；共享教师后端默认 5500。</p></details></form><div id="resolved" aria-live="polite"></div></section>`;}
function bindScenario(){ $('#scenario').addEventListener('input',e=>{config={...config,...Object.fromEntries(new FormData($('#scenario')))};if(e.target.name==='station' && /^sz(?:0[1-9]|[1-9][0-9])$/.test(config.station)){Object.assign(config,stationDefaults(config.station));for(const [key,value] of Object.entries(stationDefaults(config.station))){const el=$('#scenario').elements.namedItem(key);if(el)el.value=value;}}save();updateCommands();});$('#reset').onclick=()=>{config={...defaults};save();route();};updateCommands();}
function updateCommands(){try{const c=resolve(config);if($('#resolved'))$('#resolved').innerHTML='';if(active&&active.id!=='00-workstation') renderSteps(c);}catch(e){if($('#resolved'))$('#resolved').innerHTML=`<p class="error" role="alert">${esc(e.message)}</p>`;if($('#steps'))$('#steps').innerHTML='<p class="error" role="alert">请先到<a href="#/course/00-workstation">00 配置你的实训场景</a>修正配置，再查看操作步骤。</p>';if($('#step-nav'))$('#step-nav').innerHTML='';}}
function progressKey(i){return `${active.id}/${config.station}/${config.mode}/${i}`;}
function stepLabel(title){const labels={'任务：抓取试管，放入试管架':'试管抓取任务','为什么用仿真？':'为什么用仿真','什么是 sim-to-real 鸿沟？':'Sim-to-Real 鸿沟','你的机器人和遥控器':'机器人与遥控器','什么是 LeRobot 和 GR00T？':'LeRobot 与 GR00T'};return labels[title]||title.replace(/^第[一二三四五六七八九十]+步[：:]|^[一二三四五六七八九十]+、/,'').replace(/（[^）]*）/g,'');}
function renderSteps(c){
 const lesson=lessonContent(active,c);
 lesson.preparation.forEach((html,i)=>{const panel=$("#prep-panel-"+i);if(panel)panel.innerHTML=html;});
 selectedStep=Math.min(selectedStep,lesson.steps.length-1);
 const step=lesson.steps[selectedStep];
 $('#step-nav').innerHTML=lesson.steps.map((s,i)=>`<button role="tab" id="step-tab-${i}" aria-controls="step-panel" aria-selected="${i===selectedStep}" tabindex="${i===selectedStep?0:-1}" data-step="${i}" title="${esc(s.title)}" aria-label="${i+1}. ${esc(s.title)}"><span class="step-tab-number">${String(i+1).padStart(2,'0')}</span>${esc(stepLabel(s.title))}</button>`).join('');
 $('#steps').innerHTML=`<section id="step-panel" class="guide step-panel" role="tabpanel" aria-labelledby="step-tab-${selectedStep}" tabindex="0"><div class="step-heading"><span class="eyebrow">STEP ${selectedStep+1} / ${lesson.steps.length}</span><label class="done"><input type="checkbox" id="step-done" ${completed[progressKey(step.id)]?'checked':''}>完成</label></div><h2>${esc(step.title)}</h2>${step.html}</section><div class="step-pagination"><button id="previous-step" ${selectedStep===0?'disabled':''}>← 上一步</button><span>${selectedStep+1} / ${lesson.steps.length}</span><button id="next-step" ${selectedStep===lesson.steps.length-1?'disabled':''}>下一步 →</button></div>`;
 $('#lesson-notes').innerHTML=lesson.notes;
 const select=i=>{selectedStep=i;renderSteps(c);$('#step-tab-'+i).scrollIntoView({block:'nearest',inline:'nearest'});$('#step-panel').focus({preventScroll:true});};
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>select(+b.dataset.step));
 bindTabKeys($('#step-nav'));
 $('#previous-step').onclick=()=>select(selectedStep-1);$('#next-step').onclick=()=>select(selectedStep+1);
 $('#step-done').onchange=e=>{completed[progressKey(step.id)]=e.target.checked;save();};
 $('#steps').querySelectorAll('pre').forEach(pre=>{if(!pre.querySelector('code.language-bash'))return;const button=document.createElement('button');button.className='copy-code';button.textContent='复制命令';button.onclick=()=>copy(pre.textContent);pre.before(button);});
}
function bindTabKeys(nav){nav.onkeydown=e=>{const tabs=[...nav.querySelectorAll('[role="tab"]')];const index=tabs.indexOf(document.activeElement);if(index<0)return;let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;else if(e.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();tabs[next].click();nav.querySelectorAll('[role="tab"]')[next].focus();};}
function home(){active=null;$('#app').innerHTML=`<section class="hero"><div><span class="eyebrow">ROBOTICS · LEARN BY DOING</span><h1>连接物理和AI的<em>桥梁</em></h1><p class="hero-promise">提供大量免费线下物理AI实操课</p><div class="hero-meta"><span>4座城市</span><span>10 个课程配方</span><span>2 种算力场景</span></div></div><figure class="experiment-art"><img src="assets/robot-lab.svg" alt="动态卡通机械臂在实验台操作试管"><figcaption>机械臂实验室 · 从仿真到真实</figcaption></figure></section><section class="catalog"><div class="section-heading"><div><span class="eyebrow">COURSE RECIPES</span><h2>选择你的课程菜单</h2></div></div><div class="filters" id="filters"></div><div id="cards" class="cards"></div></section>`;let category='全部';const categories=['全部','sim2real','real2sim','Muse'];function show(){const query=searchQuery.trim().toLowerCase();const list=recipes.filter(r=>(category==='全部'||r.category===category)&&`${r.title} ${r.description} ${r.category}`.toLowerCase().includes(query));$('#filters').innerHTML=categories.map(t=>`<button class="${t===category?'selected':''}" data-filter="${t}">${t}</button>`).join('');$('#cards').innerHTML=list.map(r=>`<a class="course-card" href="#/course/${r.id}"><div class="card-top"><span class="course-index">${String(r.order).padStart(2,'0')}</span><span class="pill">sim2real</span><span class="arrow">↗</span></div><h3>${r.title}</h3><p>${r.description}</p><div class="card-foot"><span>${r.duration}</span><span>查看课程 →</span></div></a>`).join('')||(['real2sim','Muse'].includes(category)?`<p class="empty">${esc(category)} 课程 · 敬请期待</p>`:'<p class="empty">没有找到课程，试试其他关键词。</p>');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.filter;show();});}showCatalog=show;show();}
function course(r){
 active=r;selectedStep=0;showCatalog=null;
 const courseIndex=recipes.findIndex(x=>x.id===r.id), lesson=r.id==='00-workstation'?null:lessonContent(r,(()=>{try{return resolve(config);}catch{return resolve(defaults);}})());
 $('#app').innerHTML=`<div class="breadcrumbs"><a href="#/">全部课程</a><span>/</span>${esc(r.category)}<span>/</span>${esc(r.title)}</div><section class="course-heading"><span class="eyebrow">RECIPE ${String(r.order).padStart(2,'0')} · ${esc(r.duration)}</span><h1>${esc(r.title)}</h1><p>${esc(r.description)}</p></section><label class="compact-course-nav">课程目录<select id="course-select" aria-label="切换课程">${recipes.map(x=>`<option value="${x.id}" ${r.id===x.id?'selected':''}>${String(x.order).padStart(2,'0')} ${x.title}</option>`).join('')}</select></label><div class="lesson-layout"><aside class="lesson-nav"><span class="eyebrow">课程目录</span><nav id="course-directory" aria-label="课程目录">${recipes.map(x=>`<a href="#/course/${x.id}" class="${r.id===x.id?'current':''}">${String(x.order).padStart(2,'0')} ${x.title}</a>`).join('')}</nav></aside><div class="lesson-main">${r.id==='00-workstation'?scenarioForm():`<section class="preparation"><span class="eyebrow">PREPARATION</span><h2>课前准备</h2><div class="tab-menu" id="preparation-tabs" role="tablist" aria-label="课前准备">${['课程概览','前置条件'].map((t,i)=>`<button role="tab" id="prep-tab-${i}" aria-controls="prep-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-prep="${i}">${t}</button>`).join('')}</div>${lesson.preparation.map((html,i)=>`<div class="prep-panel guide" id="prep-panel-${i}" role="tabpanel" aria-labelledby="prep-tab-${i}" ${i?'hidden':''}>${html}</div>`).join('')}</section><section class="workflow"><div class="section-heading"><div><span class="eyebrow">PRACTICE GUIDE</span><h2>实操流程</h2></div><span class="muted">选择步骤，逐步完成</span></div><nav id="step-nav" class="tab-menu step-tabs" role="tablist" aria-label="实操步骤"></nav><div id="steps"></div></section><section class="guide lesson-notes"><span class="eyebrow">NOTES</span><h2>必要说明</h2><div id="lesson-notes"></div></section>`}<div class="lesson-bottom">${courseIndex>0?`<a href="#/course/${recipes[courseIndex-1].id}">← 上一课</a>`:'<span></span>'}${courseIndex<recipes.length-1?`<a href="#/course/${recipes[courseIndex+1].id}">下一课 →</a>`:'<a href="#/">返回课程首页 →</a>'}</div></div></div>`;
 $('#course-select').onchange=e=>{location.hash='#/course/'+e.target.value;};
 if(r.id==='00-workstation'){bindScenario();return;}
 document.querySelectorAll('[data-prep]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-prep]').forEach(t=>{const on=t===b;t.setAttribute('aria-selected',on);t.tabIndex=on?0:-1;$('#prep-panel-'+t.dataset.prep).hidden=!on;});});bindTabKeys($('#preparation-tabs'));updateCommands();
}
function route(){if(location.hash==='#/workstation'){location.replace('#/course/00-workstation');return;}const match=location.hash.match(/^#\/course\/([a-z0-9-]+)$/);if(match){const r=recipes.find(r=>r.id===match[1]);if(r)course(r);else{$('#app').innerHTML='<h1>课程不存在</h1><a href="#/">返回首页</a>';active=null;}}else home();document.title=active?`${active.title} · BirdBrid`:'BirdBrid · 机器人实训 Recipes';if(location.hash==='#/workstation')$('#workstation')?.scrollIntoView();else if(!active&&searchQuery.trim())$('.catalog')?.scrollIntoView();else window.scrollTo(0,0);}
$('#course-search').oninput=e=>{searchQuery=e.target.value;if(!active&&showCatalog)showCatalog();};
$('#header-search').onsubmit=e=>{e.preventDefault();if(active){location.hash='#/';}else if(showCatalog){showCatalog();$('.catalog').scrollIntoView({behavior:'smooth'});}};
window.addEventListener('hashchange',route);route();
